local utf8 = require("utf8") 

local questions = {
{question = "Cor do céu em um dia sem nuvens", answer = "AZUL", level = 1},
{question = "Animal que late", answer = "CACHORRO", level = 1},
{question = "Fruta amarela e curvada", answer = "BANANA", level = 1},
{question = "Objeto usado para escrever", answer = "LAPIS", level = 1},
{question = "Grande astro que ilumina o dia", answer = "SOL", level = 1},
{question = "Animal que mia", answer = "GATO", level = 1},
{question = "Bebida feita com frutas", answer = "SUCO", level = 1},
{question = "Lugar onde moramos", answer = "CASA", level = 1},
{question = "Objeto usado para cortar papel", answer = "TESOURA", level = 1},
{question = "Objeto que usamos nos pes", answer = "SAPATO", level = 1},
{question = "Dia que vem depois da sexta", answer = "SABADO", level = 1},
{question = "Cor do sangue", answer = "VERMELHO", level = 1},
{question = "Animal que vive no mar", answer = "PEIXE", level = 1},
{question = "Usado para enxugar o corpo", answer = "TOALHA", level = 1},
{question = "Usado para escovar os dentes", answer = "ESCOVA", level = 1},
{question = "Inseto que faz mel", answer = "ABELHA", level = 1},
{question = "Fruta vermelha pequena", answer = "MORANGO", level = 1},
{question = "Parte do corpo usada para ver", answer = "OLHO", level = 1},
{question = "Peça de roupa usada na cabeca", answer = "BONÉ", level = 1},
{question = "Cor das nuvens", answer = "BRANCO", level = 1},
{question = "Animal que tem asas e bico", answer = "PASSARO", level = 1},
{question = "Tem chaves e abre portas", answer = "FECHADURA", level = 1},
{question = "Ponto de luz no teto", answer = "LAMPADA", level = 1},
{question = "Parte do corpo que usamos para andar", answer = "PÉ", level = 1},
{question = "Brinquedo com rodas e pedais", answer = "BICICLETA", level = 1},
{question = "Usado para ver horas", answer = "RELOGIO", level = 1},
{question = "Comida redonda com queijo e molho", answer = "PIZZA", level = 1},
{question = "Usamos para sentar", answer = "CADEIRA", level = 1},
{question = "Fruta que pode ser verde ou roxa", answer = "UVA", level = 1},
{question = "Dia depois da segunda", answer = "TERCA", level = 1},
{question = "Animal de carga com orelhas grandes", answer = "BURRO", level = 2},
{question = "Fica no céu e brilha à noite", answer = "ESTRELA", level = 2},
{question = "Casa de campo feita de madeira", answer = "CABANA", level = 2},
{question = "Animal que gosta de queijo", answer = "RATO", level = 2},
{question = "Fruta com casca espinhosa e coroa", answer = "ABACAXI", level = 2},
{question = "Usado para pintar paredes", answer = "ROLO", level = 2},
{question = "Objeto que mostra reflexo", answer = "ESPELHO", level = 2},
{question = "Peça de roupa usada na praia", answer = "BIQUINI", level = 2},
{question = "Doce feito com leite e acucar", answer = "DOCE DE LEITE", level = 2},
{question = "Movimento do mar", answer = "ONDA", level = 2},
{question = "Gato selvagem de grande porte", answer = "LEAO", level = 2},
{question = "Material usado em janelas", answer = "VIDRO", level = 2},
{question = "Fica entre o joelho e o pe", answer = "PERNA", level = 2},
{question = "Molho vermelho de tomate", answer = "KETCHUP", level = 2},
{question = "Parte do corpo que escuta", answer = "ORELHA", level = 2},
{question = "Comida frita feita de batata", answer = "BATATA", level = 2},
{question = "Animal com listras pretas e brancas", answer = "ZEBRA", level = 2},
{question = "Cor do ouro", answer = "DOURADO", level = 2},
{question = "Brinquedo que sobe com vento", answer = "PIPA", level = 2},
{question = "Usado para medir o tempo", answer = "RELOGIO", level = 2},
{question = "Barco pequeno movido por remos", answer = "CANOA", level = 3},
{question = "Fruta com casca dura e branca por dentro", answer = "COCO", level = 3},
{question = "Grande felino com manchas", answer = "ONCA", level = 3},
{question = "Usado para dormir e tem travesseiro", answer = "CAMA", level = 3},
{question = "Animal que pula e tem bolsa", answer = "CANGURU", level = 3},
{question = "Pequeno inseto que pica", answer = "MOSQUITO", level = 3},
{question = "Casa de abelhas", answer = "COLMEIA", level = 3},
{question = "Animal com pescoço comprido", answer = "GIRAFA", level = 3},
{question = "Vegetal alaranjado usado em saladas", answer = "CENOURA", level = 3},
{question = "Parte da casa onde se cozinha", answer = "COZINHA", level = 3},
{question = "Ave símbolo do Brasil", answer = "ARARA", level = 3},
{question = "Flor vermelha que simboliza amor", answer = "ROSA", level = 3},
{question = "Animal que bota ovo e cacareja", answer = "GALINHA", level = 3},
{question = "Objeto usado para limpar o chão", answer = "VASSOURA", level = 3},
{question = "Inimigo do Batman", answer = "CORINGA", level = 3},
{question = "Doce feito com chocolate e granulado", answer = "BRIGADEIRO", level = 3},
{question = "Capa usada quando chove", answer = "CAPA DE CHUVA", level = 3},
{question = "Animal que tem tromba", answer = "ELEFANTE", level = 3},
{question = "Objeto com motor que voa", answer = "AVIAO", level = 3},
{question = "Lugar com areia e mar", answer = "PRAIA", level = 3},
{question = "Animal que vive no gelo", answer = "FOCA", level = 3},
{question = "Sobe montanhas e tem neve", answer = "ALPES", level = 3},
{question = "Objeto que guarda moedas", answer = "CARTEIRA", level = 3},
{question = "Inseto colorido que voa", answer = "BORBOLETA", level = 3},
{question = "Brinquedo de pelucia", answer = "URSINHO", level = 3},
{question = "Animal que muda de cor", answer = "CAMALEAO", level = 4},
{question = "Lugar com muitos livros", answer = "BIBLIOTECA", level = 4},
{question = "Inseto que tem corpo luminoso", answer = "VAGA LUME", level = 4},
{question = "Peixe usado em sushi", answer = "SALMAO", level = 4},
{question = "Animal com espinhos nas costas", answer = "PORCO ESPINHO", level = 4},
{question = "Cidade famosa pela Torre Eiffel", answer = "PARIS", level = 4},
{question = "Gato selvagem das montanhas", answer = "LINCE", level = 4},
{question = "Animal lento que carrega casa", answer = "CARACOL", level = 4},
{question = "Rei da selva", answer = "LEAO", level = 4},
{question = "Objeto que mede temperatura", answer = "TERMOMETRO", level = 4},
{question = "Animal com patas e casco duro", answer = "TARTARUGA", level = 4},
{question = "Pequeno roedor noturno", answer = "HAMSTER", level = 4},
{question = "Doce de festa com coco queimado", answer = "BEIJINHO", level = 4},
{question = "Onde se guardam os livros em casa", answer = "ESTANTE", level = 4},
{question = "O que usamos para ver estrelas", answer = "TELESCOPIO", level = 4},
{question = "Animal marinho com tentaculos", answer = "POLVO", level = 4},
{question = "Flor que nasce no pantano", answer = "LODO", level = 4},
{question = "Lugar cheio de arvores e bichos", answer = "FLORESTA", level = 4},
{question = "Pássaro de penas coloridas", answer = "TUCANO", level = 4},
{question = "Objeto que segura papéis", answer = "CLIPS", level = 4},
{question = "Objeto com cordas para tocar musica", answer = "VIOLAO", level = 4},
{question = "Tipo de casa no campo", answer = "SITIO", level = 4},
{question = "Objeto usado para ver de longe", answer = "BINOCULO", level = 4},
{question = "Animal peludo que hiberna", answer = "URSO", level = 4},
{question = "Comida típica das festas juninas feita com milho", answer = "PAMONHA", level = 5},
{question = "Rei dos mares na mitologia grega", answer = "POSEIDON", level = 5},
{question = "Animal com bico longo que come peixe", answer = "TUIUIU", level = 5},
{question = "Brinquedo que gira com o vento", answer = "CATAVENTO", level = 5},
{question = "Peça de roupa que cobre as pernas", answer = "CALCA", level = 5},
{question = "Fruta de casca grossa e polpa vermelha", answer = "MELANCIA", level = 5},
{question = "Animal com patas de pato e bico", answer = "ORNITORRINCO", level = 5},
{question = "Ave que repete o que escuta", answer = "PAPAGAIO", level = 5},
{question = "Animal que vive em cavernas", answer = "MORCEGO", level = 5},
{question = "Instrumento com teclas", answer = "PIANO", level = 5},
{question = "Peixe que infla ao ser ameaçado", answer = "BAIACU", level = 5},
{question = "Lugar para ver peixes marinhos", answer = "AQUARIO", level = 5},
{question = "Doce feito com coco e enrolado", answer = "BEIJINHO", level = 5},
{question = "Fruta com espinhos e cheiro forte", answer = "JACA", level = 5},
{question = "Estrela maior do sistema solar", answer = "SOL", level = 5},
{question = "Gato selvagem com nome de carro", answer = "JAGUAR", level = 5},
{question = "Vegetal usado para fazer vinagre", answer = "BETERRABA", level = 5},
{question = "Tipo de energia gerada pelo sol", answer = "SOLAR", level = 5},
{question = "Doce enrolado com chocolate e coco", answer = "BRIGADEIRO", level = 5},
{question = "Objeto que serve para iluminar", answer = "LANTERNA", level = 5},
{question = "Ave noturna que gira a cabeca", answer = "CORUJA", level = 6},
{question = "Peixe com corpo achatado e veneno", answer = "RAIA", level = 6},
{question = "Casa subterranea de formigas", answer = "FORMIGUEIRO", level = 6},
{question = "Montanha com lava", answer = "VULCAO", level = 6},
{question = "Inseto que salta e canta", answer = "GRILO", level = 6},
{question = "Animal com antenas e muitas patas", answer = "CENTOPEIA", level = 6},
{question = "Animal que vive em agua doce e pula", answer = "SAPO", level = 6},
{question = "Doce feito com amendoim e acucar", answer = "PAÇOCA", level = 6},
{question = "Objeto usado para ver o tempo", answer = "RELOGIO", level = 6},
{question = "Animal que sobe em arvores e tem rabo", answer = "MACACO", level = 6},
{question = "Animal africano com chifre", answer = "RINOCERONTE", level = 6},
{question = "Ave que corre e nao voa", answer = "EMA", level = 6},
{question = "Comida feita de arroz cru enrolado", answer = "SUSHI", level = 6},
{question = "Objeto que mostra direcoes", answer = "BUSSOLA", level = 6},
{question = "Brinquedo que pula no chao", answer = "BOLA", level = 6},
{question = "Lugar onde ha muita areia", answer = "DESERTO", level = 6},
{question = "Arte de dobrar papel", answer = "ORIGAMI", level = 6},
{question = "Inseto social que vive em colmeia", answer = "ABELHA", level = 6},
{question = "Flor usada para fazer chá", answer = "CAMOMILA", level = 6},
{question = "Doce em formato de espiral", answer = "PIRULITO", level = 6},
{question = "Cobra venenosa da floresta", answer = "JARARACA", level = 7},
{question = "Molusco com concha em espiral", answer = "CARACOL", level = 7},
{question = "Arte japonesa com peixe cru", answer = "SUSHI", level = 7},
{question = "Ave que vive no gelo e anda ereta", answer = "PINGUIM", level = 7},
{question = "Animal que tem bracos com ventosas", answer = "POLVO", level = 7},
{question = "Grande felino das neves", answer = "LEOPARDO", level = 7},
{question = "Cavalo pequeno e robusto", answer = "PONEI", level = 7},
{question = "Animal que cava e tem garras", answer = "TATU", level = 7},
{question = "Peixe usado para fazer sashimi", answer = "SALMAO", level = 7},
{question = "Barulho forte no céu com relampago", answer = "TROVAO", level = 7},
{question = "Objeto que mede a pressao do ar", answer = "BAROMETRO", level = 7},
{question = "Mamifero que vive em cavernas", answer = "MORCEGO", level = 7},
{question = "Camada azul que protege a Terra", answer = "OZONIO", level = 7},
{question = "Vegetal usado no guacamole", answer = "ABACATE", level = 7},
{question = "Animal de casco que vive no mar", answer = "TARTARUGA", level = 7},
{question = "Esporte com raquete e peteca", answer = "BADMINTON", level = 7},
{question = "Cobra que se enrola em galhos", answer = "SUCURI", level = 7},
{question = "Peixe perigoso com dentes afiados", answer = "PIRANHA", level = 7},
{question = "Objeto que detecta calor", answer = "TERMOGRAFO", level = 7},
{question = "Vegetal roxo em forma de bulbo", answer = "BETERRABA", level = 7},
{question = "Animal com corcova que vive no deserto", answer = "CAMELO", level = 8},
{question = "Peixe eletrico da agua doce", answer = "PORAQUE", level = 8},
{question = "Ave de rapina que simboliza poder", answer = "AGUIA", level = 8},
{question = "Animal marinho com oito bracos", answer = "POLVO", level = 8},
{question = "Objeto que indica o norte", answer = "BUSSOLA", level = 8},
{question = "Camada da Terra abaixo da crosta", answer = "MANTO", level = 8},
{question = "Animal com listras pretas e brancas", answer = "ZEBRA", level = 8},
{question = "Inseto com asas transparentes", answer = "LIBELULA", level = 8},
{question = "Animal de grande tromba", answer = "ELEFANTE", level = 8},
{question = "Semente usada para fazer pao", answer = "TRIGO", level = 8},
{question = "Peixe com corpo achatado e ferrão", answer = "ARRAIA", level = 8},
{question = "Planta carnivora que atrai insetos", answer = "DIONEA", level = 8},
{question = "Molusco marinho com concha espiral", answer = "NAUTILUS", level = 8},
{question = "Gato selvagem que vive no gelo", answer = "LINCE", level = 8},
{question = "Ave que faz ninho em falésias", answer = "ANDORINHA", level = 8},
{question = "Fenomeno natural de luz no céu", answer = "AURORA", level = 8},
{question = "Arvore simbolo do Brasil", answer = "IPÊ", level = 8},
{question = "Mamifero que vive na agua e salta", answer = "GOLFINHO", level = 8},
{question = "Vegetal que cresce em bambuzal", answer = "BAMBU", level = 8},
{question = "Animal que se enrola em forma de espiral", answer = "CARAMUJO", level = 8},
{question = "Fenomeno com luzes coloridas nos polos", answer = "AURORA", level = 9},
{question = "Planta carnivora que fecha rapido", answer = "DIONEA", level = 9},
{question = "Animal que muda de sexo naturalmente", answer = "PEIXE PALHAÇO", level = 9},
{question = "Molusco com concha dividido em camaras", answer = "NAUTILUS", level = 9},
{question = "Peixe de dentes afiados e perigoso", answer = "PIRANHA", level = 9},
{question = "Ave marinha com bico curvado", answer = "ATOBÁ", level = 9},
{question = "Animal africano com dois chifres", answer = "RINOCERONTE", level = 9},
{question = "Especie de felino que vive no gelo", answer = "LINCE", level = 9},
{question = "Animal marinho com espinhos e globoso", answer = "OURICO", level = 9},
{question = "Vento giratorio muito destrutivo", answer = "TORNADO", level = 9},
{question = "Formacao subterranea com cristais", answer = "GEODA", level = 9},
{question = "Animal com patas aderentes ao vidro", answer = "LAGARTIXA", level = 9},
{question = "Peixe de aguas profundas com luz", answer = "PEIXE LUZ", level = 9},
{question = "Animal que vive em colmeia", answer = "ABELHA", level = 9},
{question = "Objeto usado para medir sismos", answer = "SISMOGRAFO", level = 9},
{question = "Planta que cresce em ambiente salgado", answer = "MANGUE", level = 9},
{question = "Ave que mergulha para pescar", answer = "MERGULHAO", level = 9},
{question = "Peixe com boca em formato de disco", answer = "ARUANA", level = 9},
{question = "Animal marinho de corpo gelatinoso", answer = "AGUA VIVA", level = 9},
{question = "Ave que corre e vive na Africa", answer = "AVESTRUZ", level = 9},
{question = "Mamifero marinho que usa ecolocalizacao", answer = "GOLFINHO", level = 10},
{question = "Fenomeno luminoso causado por eletricidade", answer = "RELAMPEJO", level = 10},
{question = "Peixe com dentes que parece sorrir", answer = "PACU", level = 10},
{question = "Animal que libera tinta ao se defender", answer = "LULA", level = 10},
{question = "Unico mamifero com asas verdadeiras", answer = "MORCEGO", level = 10},
{question = "Inseto que imita graveto", answer = "BICHO PAU", level = 10},
{question = "Ave com penas azuis e cauda longa", answer = "ARARINHA", level = 10},
{question = "Planta que cresce em zona alagada", answer = "MANGUE", level = 10},
{question = "Animal que se enrola ao redor da presa", answer = "JIBOIA", level = 10},
{question = "Peixe de agua doce com escamas grossas", answer = "TAMBAQUI", level = 10},
{question = "Ave que dorme em voo", answer = "ANDORINHA", level = 10},
{question = "Peixe com formato achatado e olhos no topo", answer = "LINGUADO", level = 10},
{question = "Animal que cava tuneis no solo", answer = "TOUPEIRA", level = 10},
{question = "Animal de corpo gelatinoso e veneno", answer = "AGUA VIVA", level = 10},
{question = "Flor que abre apenas a noite", answer = "DAMALUNA", level = 10},
{question = "Animal com corpo segmentado e antenas", answer = "CIGARRA", level = 10},
{question = "Reptil que troca de pele", answer = "SERPENTE", level = 10},
{question = "Inseto com asas e corpo transparente", answer = "LIBELULA", level = 10},
{question = "Peixe com bico longo e afiado", answer = "ESPADA", level = 10},
{question = "Arvore de madeira nobre brasileira", answer = "PAU BRASIL", level = 10},
}

-- Function to remove accents from a string
local function remove_accents(str)
  local accent_map = {
    ['Á']='A', ['À']='A', ['Â']='A', ['Ã']='A', ['Ä']='A',
    ['É']='E', ['È']='E', ['Ê']='E', ['Ë']='E',
    ['Í']='I', ['Ì']='I', ['Î']='I', ['Ï']='I',
    ['Ó']='O', ['Ò']='O', ['Ô']='O', ['Õ']='O', ['Ö']='O',
    ['Ú']='U', ['Ù']='U', ['Û']='U', ['Ü']='U',
    ['Ç']='C',
    ['á']='a', ['à']='a', ['â']='a', ['ã']='a', ['ä']='a',
    ['é']='e', ['è']='e', ['ê']='e', ['ë']='e',
    ['í']='i', ['ì']='i', ['î']='i', ['ï']='i',
    ['ó']='o', ['ò']='o', ['ô']='o', ['õ']='o', ['ö']='o',
    ['ú']='u', ['ù']='u', ['û']='u', ['ü']='u',
    ['ç']='c',
    ['É']='E', ['é']='e', ['Ê']='E', ['ê']='e', ['Í']='I', ['í']='i', ['Ó']='O', ['ó']='o', ['Ú']='U', ['ú']='u', ['Â']='A', ['â']='a', ['Ô']='O', ['ô']='o', ['À']='A', ['à']='a', ['Ã']='A', ['ã']='a', ['Õ']='O', ['õ']='o', ['Ç']='C', ['ç']='c', ['Ü']='U', ['ü']='u', ['Ï']='I', ['ï']='i', ['Ö']='O', ['ö']='o', ['Ë']='E', ['ë']='e', ['Ä']='A', ['ä']='a'
  }
  local result = {}
  for _, codepoint in utf8.codes(str) do
    local char = utf8.char(codepoint)
    table.insert(result, accent_map[char] or char)
  end
  return table.concat(result)
end

for i, q in ipairs(questions) do
  q.answer = remove_accents(q.answer)
end

return questions
