local questions = {
    {question = "Plural de animais que miam", answer = "GATOS"},
    {question = "Maior planeta do sistema solar", answer = "JUPITER"},
    {question = "Cor do céu em um dia claro", answer = "AZUL"},
    {question = "Animal que late", answer = "CACHORRO"},
    {question = "Capital da França", answer = "PARIS"},
    {question = "Instrumento musical de teclas", answer = "PIANO"},
    {question = "Maior oceano do mundo", answer = "PACIFICO"},
    {question = "Cor da grama", answer = "VERDE"},
    {question = "Primeiro mês do ano", answer = "JANEIRO"},
    {question = "Inseto que produz mel", answer = "ABELHA"},
    {question = "Elemento químico com símbolo Au", answer = "OURO"},
    {question = "Autor de Dom Quixote", answer = "CERVANTES"},
    {question = "Maior deserto do mundo", answer = "SAARA"},
    {question = "Teorema matemático de Pitágoras", answer = "PITAGORAS"},
    {question = "Primeiro presidente do Brasil", answer = "DEODORO"},
    {question = "Descobridor da penicilina", answer = "FLEMING"},
    {question = "Maior número primo conhecido em 2024", answer = "MERSENNE"},
    {question = "Cidade mais populosa do mundo", answer = "TOQUIO"},
    {question = "Cor do sol ao entardecer", answer = "ALARANJADO"},
    {question = "Metal usado em fios elétricos", answer = "COBRE"},
    {question = "Animal símbolo da Austrália", answer = "CANGURU"},
    {question = "Esporte jogado com raquete e peteca", answer = "BADMINTON"},
    {question = "Monumento famoso na Índia", answer = "TAJMAHAL"},
    {question = "Gás essencial à respiração", answer = "OXYGENIO"},
    {question = "Maior animal terrestre", answer = "ELEFANTE"},
    {question = "País em que se fala mandarim", answer = "CHINA"},
    {question = "Autor de 'A Metamorfose'", answer = "KAFKA"},
    {question = "Instrumento musical com arco", answer = "VIOLINO"},
    {question = "Planeta conhecido como estrela d'alva", answer = "VENUS"},
    {question = "Nome do satélite natural da Terra", answer = "LUA"},
    {question = "Pintor de 'Guernica'", answer = "PICASSO"},
    {question = "Maior cordilheira do mundo", answer = "ANDES"},
    {question = "Órgão responsável pelo bombeamento do sangue", answer = "CORACAO"},
    {question = "Escritor de 'O Pequeno Príncipe'", answer = "SAINT EXUPERY"},
    {question = "Animal com pescoço muito comprido", answer = "GIRAFAS"},
    {question = "Capital do Japão", answer = "TOQUIO"},
    {question = "Nome da floresta amazônica em inglês", answer = "AMAZON"},
    {question = "Língua oficial do Egito", answer = "ARABE"},
    {question = "Parte do corpo usada para ouvir", answer = "ORELHA"},
    {question = "Nome da figura geométrica com três lados", answer = "TRIANGULO"},
    {question = "Planeta vermelho do sistema solar", answer = "MARTE"},
    {question = "Doce feito com cacau", answer = "CHOCOLATE"},
    {question = "Ave que imita sons humanos", answer = "PAPAGAIO"},
    {question = "Peça do corpo usada para andar", answer = "PERNAS"},
    {question = "Doença causada pelo vírus HIV", answer = "AIDS"},
    {question = "Fruta cítrica de casca laranja", answer = "LARANJA"},
    {question = "Gênero musical originado na Jamaica", answer = "REGGAE"},
    {question = "Nome da capital do Canadá", answer = "OTTAWA"},
    {question = "Molécula essencial para a vida", answer = "AGUA"},
    {question = "Rei francês que dizia 'O Estado sou eu'", answer = "LUIS"},
    {question = "Nome do dinossauro carnívoro mais famoso", answer = "TIRANOSSAURO"},
    {question = "Animal com casco usado em corridas", answer = "CAVALO"},
    {question = "Líquido vermelho que circula no corpo", answer = "SANGUE"},
    {question = "Autor brasileiro de 'Grande Sertão: Veredas'", answer = "GUIMARAES"},
    {question = "Cidade onde está a Estátua da Liberdade", answer = "NOVA YORK"},
    {question = "Elemento químico com símbolo Fe", answer = "FERRO"},
    {question = "Nome do processo das plantas produzirem alimento", answer = "FOTOSSINTESE"},
    {question = "Nome do satélite artificial que orbita a Terra", answer = "SATELITE"},
    {question = "Pequeno roedor doméstico", answer = "HAMSTER"},
     {question = "Maior mamífero marinho", answer = "BALEIA AZUL"},
    {question = "Cidade conhecida como a terra da garoa", answer = "SAO PAULO"},
    {question = "Continente onde fica o Egito", answer = "AFRICA"},
    {question = "Nome do satélite que orbita Marte", answer = "FOBOS"},
    {question = "Nome da deusa do amor na mitologia grega", answer = "AFRODITE"},
    {question = "Objeto usado para ver estrelas", answer = "TELESCOPIO"},
    {question = "Capital do Canadá", answer = "OTTAWA"},
    {question = "Maior país em extensão territorial", answer = "RUSSIA"},
    {question = "Animal símbolo do WWF", answer = "PANDA"},
    {question = "Inseto com corpo listrado e ferrão", answer = "VESPA"},
    {question = "Cor da pele do personagem Shrek", answer = "VERDE"},
    {question = "Alimento feito com leite coagulado", answer = "QUEIJO"},
    {question = "Forma sólida da água", answer = "GELO"},
    {question = "Líder político que lutou contra o apartheid", answer = "MANDELA"},
    {question = "Nome do continente gelado", answer = "ANTARTIDA"},
    {question = "Sentido utilizado para saborear alimentos", answer = "PALADAR"},
    {question = "Nome da primeira mulher no espaço", answer = "TERESKOVA"},
    {question = "Matéria que estuda números", answer = "MATEMATICA"},
    {question = "Principal astro do sistema solar", answer = "SOL"},
    {question = "A parte do corpo responsável pela visão", answer = "OLHOS"},
    {question = "Rei do pop", answer = "MICHAEL JACKSON"},
    {question = "Doença viral combatida com vacina tríplice viral", answer = "SARAMPO"},
    {question = "Nome do lugar onde vivem os cangurus", answer = "AUSTRALIA"},
    {question = "Parte do computador onde se vê imagens", answer = "MONITOR"},
    {question = "Profissional que faz cirurgias", answer = "CIRURGIAO"},
    {question = "Nome do gás que as plantas absorvem", answer = "DIOXIDO CARBONO"},
    {question = "Maior cadeia de montanhas da América do Sul", answer = "ANDES"},
    {question = "Cidade famosa pelas pirâmides", answer = "CAIRO"},
    {question = "Material transparente usado em janelas", answer = "VIDRO"},
    {question = "Pequena embarcação usada para pesca", answer = "CANOA"},
    {question = "Fruta rica em potássio", answer = "BANANA"},
    {question = "Peça de roupa usada no pé", answer = "MEIA"},
    {question = "Principal órgão do sistema nervoso", answer = "CEBEREBRO"},
    {question = "Capital da Argentina", answer = "BUENOS AIRES"},
    {question = "Objeto que mostra as horas", answer = "RELOGIO"},
    {question = "Metal precioso muito usado em joias", answer = "OURO"},
    {question = "Filme com robôs alienígenas que viram veículos", answer = "TRANSFORMERS"},
    {question = "Parte da planta que cresce embaixo da terra", answer = "RAIZ"},
    {question = "Nome da nave usada pelos astronautas da Apollo", answer = "COLUMBIA"},
    {question = "Doença causada por falta de insulina", answer = "DIABETES"},
    {question = "País onde se originou o sushi", answer = "JAPAO"},
    {question = "Comida típica das festas juninas feita com milho", answer = "PAMONHA"},
    {question = "Líquido inflamável usado como combustível", answer = "GASOLINA"},
}

return questions
